// web/src/lib/components/layout/ThemeToggle.svelte
<script lang="ts">
  import { theme } from '$lib/stores/theme';
</script>

<button
  type="button"
  onclick={() => theme.toggle()}
  aria-label="Toggle theme"
  class="inline-flex items-center gap-2 px-3 py-1.5 text-caption uppercase tracking-[0.2em] text-ink-shade hover:text-ink transition-colors"
>
  <svg width="14" height="14" viewBox="0 0 14 14" aria-hidden="true">
    <circle cx="7" cy="7" r="3.2" fill="none" stroke="currentColor" stroke-width="1" />
    <path
      d="M7 1 L7 2.5 M7 11.5 L7 13 M1 7 L2.5 7 M11.5 7 L13 7 M2.5 2.5 L3.5 3.5 M10.5 10.5 L11.5 11.5 M11.5 2.5 L10.5 3.5 M3.5 10.5 L2.5 11.5"
      stroke="currentColor"
      stroke-width="1"
      stroke-linecap="round"
      class="dark:hidden"
    />
    <path
      d="M9.5 5 a4 4 0 1 1 -4.5 4.5 a3.2 3.2 0 0 0 4.5 -4.5z"
      fill="currentColor"
      class="hidden dark:block"
    />
  </svg>
  <span class="hidden sm:inline">{$theme === 'dark' ? 'dark' : 'light'}</span>
</button>

// site/src/components/layout/ThemeToggle.tsx
import { useEffect, useState } from 'react';

export default function ThemeToggle() {
  const [isDark, setIsDark] = useState(false);
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
    const darkMode = document.documentElement.classList.contains('dark');
    setIsDark(darkMode);
  }, []);

  const toggle = () => {
    const html = document.documentElement;
    html.classList.toggle('dark');
    setIsDark(!isDark);
    localStorage.setItem('theme', isDark ? 'light' : 'dark');
  };

  if (!mounted) return null;

  return (
    <button
      onClick={toggle}
      className="p-2 rounded-md text-ink-600 dark:text-ink-400 hover:text-sepia-500 transition-colors"
      aria-label="Toggle dark mode"
    >
      {isDark ? (
        <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z" />
        </svg>
      ) : (
        <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 20 20">
          <path fillRule="evenodd" d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zM4.323 4.323a1 1 0 011.414 0l.707.707a1 1 0 11-1.414 1.414l-.707-.707a1 1 0 010-1.414zm11.354 0a1 1 0 010 1.414l-.707.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM4 10a1 1 0 011-1h1a1 1 0 110 2H5a1 1 0 01-1-1zm12 0a1 1 0 011-1h1a1 1 0 110 2h-1a1 1 0 01-1-1zm-12.657 6.657a1 1 0 010-1.414l.707-.707a1 1 0 111.414 1.414l-.707.707a1 1 0 01-1.414 0zm11.314 0a1 1 0 111.414-1.414l.707.707a1 1 0 11-1.414 1.414l-.707-.707zM10 16a1 1 0 011-1h1a1 1 0 110 2h-1a1 1 0 01-1-1z" clipRule="evenodd" />
        </svg>
      )}
    </button>
  );
}
