// web/app/[lang]/process/page.tsx
import { notFound } from "next/navigation";
import { getDict, isLang, type Lang } from "@/lib/i18n";
import RevealOnScroll from "@/components/motion/RevealOnScroll";
import SceneEightBreaths from "@/components/home/SceneEightBreaths";

export default async function ProcessPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  if (!isLang(lang)) notFound();
  const dict = getDict(lang as Lang);
  const isZh = lang === "zh";

  return (
    <main className="text-ink pt-24">
      <RevealOnScroll>
        <header className="mx-auto max-w-3xl px-6 py-12 text-center">
          <h1 className="mb-2 font-masthead text-[var(--fs-pull)] font-semibold">
            {dict.eightBreaths.title}
          </h1>
          <p className="text-ink-warm" style={{ fontFamily: "var(--font-display-script)", fontSize: "1.5rem" }}>
            {dict.eightBreaths.subtitle}
          </p>
        </header>
      </RevealOnScroll>

      <SceneEightBreaths dict={dict} />

      <RevealOnScroll>
        <footer className="mx-auto max-w-3xl px-6 py-24 text-center">
          <blockquote
            className="m-0 text-ink-warm"
            style={{
              fontFamily: "var(--font-display-script)",
              fontSize: "clamp(1.6rem, 3vw, 2.2rem)",
            }}
          >
            {isZh ? "一筆一畫，找回安靜。" : "One stroke, one breath. Stillness returned."}
          </blockquote>
        </footer>
      </RevealOnScroll>
    </main>
  );
}

// web/src/routes/[lang=lang]/process/+page.svelte
<script lang="ts">
  import SceneEightBreaths from '$lib/components/home/SceneEightBreaths.svelte';
  import RevealOnScroll from '$lib/components/primitives/RevealOnScroll.svelte';
  import { t, type Lang } from '$lib/i18n';

  type Props = { data: { lang: Lang; dict: Record<string, unknown> } };
  let { data }: Props = $props();
  const dict = $derived(data.dict);
  const lang = $derived(data.lang);
</script>

<svelte:head>
  <title>{t(dict, 'nav.process')} — {t(dict, 'site.title')}</title>
</svelte:head>

<main class="process">
  <RevealOnScroll>
    <header class="page-header">
      <h1 class="title">{t(dict, 'eightBreaths.title')}</h1>
      <p class="intro">{t(dict, 'eightBreaths.subtitle')}</p>
    </header>
  </RevealOnScroll>

  <SceneEightBreaths {dict} {lang} />

  <RevealOnScroll>
    <footer class="closing">
      <blockquote>
        <p>{lang === 'zh' ? '一筆一畫，找回安靜。' : 'One stroke, one breath. Stillness returned.'}</p>
      </blockquote>
    </footer>
  </RevealOnScroll>
</main>

<style>
  .process {
    color: var(--ink);
  }
  .page-header {
    text-align: center;
    padding: 4rem 1.5rem 2rem;
    max-width: 60rem;
    margin: 0 auto;
  }
  .title {
    font-family: var(--font-masthead);
    font-size: var(--fs-pull);
    font-weight: 600;
    margin: 0 0 0.6rem;
  }
  .intro {
    font-family: var(--font-display-script);
    color: var(--ink-warm);
    font-size: 1.5rem;
    margin: 0;
  }
  .closing {
    text-align: center;
    padding: 4rem 1.5rem 6rem;
  }
  .closing blockquote {
    margin: 0;
    font-family: var(--font-display-script);
    font-size: clamp(1.6rem, 3vw, 2.2rem);
    color: var(--ink-warm);
  }
</style>
