// web/components/motion/SketchBorder.tsx
"use client";

import { motion, useReducedMotion } from "framer-motion";
import { useEffect, useMemo, useRef, useState } from "react";
import { wobblyRect, dot } from "@/lib/tangles/geometry";
import { makeRng } from "@/lib/tangles/rng";

type Props = {
  children: React.ReactNode;
  seed?: string;
  pad?: number;
  className?: string;
};

/**
 * Wraps content in a ResizeObserver-tracked SVG that draws four corner
 * dots followed by a wobbly hand-drawn pencil border on enter.
 */
export default function SketchBorder({ children, seed = "section", pad = 28, className }: Props) {
  const reduce = useReducedMotion();
  const hostRef = useRef<HTMLDivElement>(null);
  const [size, setSize] = useState({ w: 0, h: 0 });

  useEffect(() => {
    if (!hostRef.current) return;
    const el = hostRef.current;
    const ro = new ResizeObserver(() => setSize({ w: el.offsetWidth, h: el.offsetHeight }));
    ro.observe(el);
    setSize({ w: el.offsetWidth, h: el.offsetHeight });
    return () => ro.disconnect();
  }, []);

  const paths = useMemo(() => {
    if (size.w === 0 || size.h === 0) return null;
    const rng = makeRng(seed);
    const inset = pad;
    const rect = { x: inset, y: inset, w: size.w - inset * 2, h: size.h - inset * 2 };
    return {
      dots: [
        dot(rect.x, rect.y, 2.4),
        dot(rect.x + rect.w, rect.y, 2.4),
        dot(rect.x + rect.w, rect.y + rect.h, 2.4),
        dot(rect.x, rect.y + rect.h, 2.4),
      ],
      border: wobblyRect(rect, rng, 2, 28),
    };
  }, [size, seed, pad]);

  return (
    <div ref={hostRef} className={["relative", className].filter(Boolean).join(" ")}>
      {paths && (
        <motion.svg
          className="pointer-events-none absolute inset-0 z-0 h-full w-full"
          viewBox={`0 0 ${size.w} ${size.h}`}
          preserveAspectRatio="none"
          aria-hidden="true"
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, margin: "-12% 0px" }}
        >
          {paths.dots.map((d, i) => (
            <motion.path
              key={`dot-${i}`}
              d={d}
              fill="var(--ink-pencil)"
              variants={{
                hidden: { opacity: 0 },
                visible: { opacity: 1, transition: { duration: 0.25, delay: reduce ? 0 : i * 0.18 } },
              }}
            />
          ))}
          <motion.path
            d={paths.border}
            fill="none"
            stroke="var(--ink-pencil)"
            strokeWidth={1.2}
            strokeLinecap="round"
            strokeLinejoin="round"
            vectorEffect="non-scaling-stroke"
            variants={{
              hidden: { pathLength: reduce ? 1 : 0 },
              visible: {
                pathLength: 1,
                transition: { duration: reduce ? 0 : 1.4, delay: reduce ? 0 : 0.8, ease: [0.22, 1, 0.36, 1] },
              },
            }}
          />
        </motion.svg>
      )}
      <div className="relative z-10">{children}</div>
    </div>
  );
}

// web/src/lib/components/primitives/SketchBorder.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { wobblyRect } from '$lib/tangles/geometry';
  import { makeRng } from '$lib/tangles/rng';
  import type { Snippet } from 'svelte';

  type Props = {
    seed?: string;
    jitter?: number;
    color?: string;
    width?: number;
    inset?: number;
    double?: boolean;
    children: Snippet;
  };
  let {
    seed = 'sketch',
    jitter = 1.6,
    color = 'currentColor',
    width = 1,
    inset = 6,
    double = false,
    children
  }: Props = $props();

  let host: HTMLDivElement | null = $state(null);
  let w = $state(0);
  let h = $state(0);

  onMount(() => {
    if (!host) return;
    const ro = new ResizeObserver(() => {
      const rect = host!.getBoundingClientRect();
      w = rect.width;
      h = rect.height;
    });
    ro.observe(host);
    return () => ro.disconnect();
  });

  const rng1 = $derived(makeRng(seed));
  const path1 = $derived(
    w > 0 && h > 0
      ? wobblyRect({ x: inset, y: inset, w: w - inset * 2, h: h - inset * 2 }, rng1, jitter, 18)
      : ''
  );
  const rng2 = $derived(makeRng(seed + 'b'));
  const path2 = $derived(
    double && w > 0 && h > 0
      ? wobblyRect(
          { x: inset + 3, y: inset + 3, w: w - inset * 2 - 6, h: h - inset * 2 - 6 },
          rng2,
          jitter * 0.7,
          18
        )
      : ''
  );
</script>

<div class="wrap" bind:this={host}>
  {#if w > 0 && h > 0}
    <svg class="border" viewBox="0 0 {w} {h}" aria-hidden="true">
      <path d={path1} fill="none" stroke={color} stroke-width={width} stroke-linejoin="round" />
      {#if double}
        <path d={path2} fill="none" stroke={color} stroke-width={width * 0.6} opacity="0.6" />
      {/if}
    </svg>
  {/if}
  <div class="content">
    {@render children()}
  </div>
</div>

<style>
  .wrap {
    position: relative;
    display: block;
  }
  .border {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    pointer-events: none;
  }
  .content {
    position: relative;
    z-index: 1;
  }
</style>
